#Set it to true to show the player's name on the grave
show-memorial-name: true
# set it to true to limit the spawning grave, which means that while the dead player's spawn grave 
# is still alive, it won't spawn another grave when the player dies.
limit-spawn: true
# Set it to true so that graves can despawn
despawn: true
# Despawn Grave Time in Seconds
despawn-time: 40
# Graves spawn in which worlds? if you want graves spawn only in specific worlds, add world names like this format:
#  worlds:
#    - World
#    - End
worlds: []